CREATE TABLE GRUPE (GR_IME VARCHAR(10) DEFAULT ''  NOT NULL, NAZIV VARCHAR(25) DEFAULT ''  NOT NULL, PRIMARY KEY (GR_IME));


INSERT INTO NWTIS.GRUPE (GR_IME, NAZIV) 
	VALUES ('admin', 'Administratori');
