CREATE TABLE POLAZNICI (KOR_IME VARCHAR(10) DEFAULT ''  NOT NULL, IME VARCHAR(25) DEFAULT ''  NOT NULL, PREZIME VARCHAR(25) DEFAULT ''  NOT NULL, LOZINKA VARCHAR(20) DEFAULT ''  NOT NULL, EMAIL_ADRESA VARCHAR(40) DEFAULT ''  NOT NULL, VRSTA INTEGER DEFAULT 1  NOT NULL, PRIMARY KEY (KOR_IME));

INSERT INTO NWTIS.POLAZNICI (KOR_IME, IME, PREZIME, LOZINKA, EMAIL_ADRESA, VRSTA) 
	VALUES ('admin', 'Iva', 'Zec', '123456', 'admin@foi.hr', 0);


