CREATE TABLE POLAZNICI_GRUPE (KOR_IME VARCHAR(10) DEFAULT ''  NOT NULL, GR_IME VARCHAR(10) DEFAULT ''  NOT NULL, PRIMARY KEY (KOR_IME, GR_IME));


INSERT INTO NWTIS.POLAZNICI_GRUPE (KOR_IME, GR_IME) 
	VALUES ('pero', 'admin');
