CREATE TABLE providers (
  ProviderId int NOT NULL DEFAULT 1,
  ProviderName varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (ProviderId)
);

INSERT INTO providers (ProviderId, ProviderName) VALUES
(3, 'Earth Networks Inc'),
(4, 'NMS - METAR'),
(10, 'NMS - SYNOP'),
(17, 'Coastal-Marine Automated Network'),
(19, 'EPA AirNow'),
(20, 'Alaska DOT'),
(21, 'Alaska Mesonet'),
(23, 'Citizen Weather Observers Program'),
(24, 'NOAA Air Resources Laboratory Field Research Division'),
(27, 'California-Hydro'),
(28, 'Colorado Avalanche Information Center'),
(29, 'Colorado DOT'),
(30, 'Colorado Public Highway Authority'),
(31, 'Air Resources Laboratory DC Mesonet'),
(33, 'Delaware Environmental Observing System'),
(36, 'Florida Mesonet'),
(39, 'GLOBE Program'),
(40, 'Gulf of Maine Ocean Observing System'),
(41, 'ESRL/GSD Ground-Based GPS'),
(42, 'Hydrometeorological Automated Data System'),
(43, 'Iowa DOT'),
(45, 'Indiana Dep of Transportation'),
(46, 'INTERNET'),
(47, 'Idaho DOT'),
(49, 'Kentucky Mesonet'),
(50, 'Kentucky Transportation Cabinet RWIS'),
(51, 'Lower Colorado River Authority'),
(53, 'Multi-Agency Profiler Surface Observations'),
(54, 'Maryland DOT'),
(55, 'Maine DOT'),
(56, 'Cooperative Mesonets in the Western U.S.'),
(57, 'MISC'),
(59, 'Minnesota DOT'),
(60, 'University of Missouri Extension Commercial Agriculture '),
(61, 'Marquette WFO '),
(63, 'North Dakota DOT'),
(64, 'Nebraska Dep of Roads'),
(65, 'National Estuarine Research Reserve System'),
(66, 'New Hampshire DOT'),
(67, 'New Jersey Weather and Climate Network'),
(68, 'Non-Federal AWOS'),
(69, 'National Ocean Service - Water Level Observation Network'),
(70, 'National Ocean Service - Physical Oceanographic Real-Time System'),
(71, 'Ohio DOT'),
(75, 'Remote Automated Weather Stations'),
(76, 'Radiometer'),
(77, 'South Florida Water Management District'),
(78, 'Denver Urban Drainage and Flood Control District'),
(79, 'Virginia DOT'),
(80, 'Vermont AOT'),
(81, 'Wisconsin DOT'),
(82, 'West Texas Mesonet'),
(85, 'Wyoming DOT'),
(86, 'Climate Reference Network'),
(87, 'New England Pilot Project'),
(88, 'Surface Airways Observation Network'),
(90, 'West Virginia Dep of Transportation'),
(91, 'ESRL/GSD Ground-Based GPS'),
(94, 'Nevada DOT'),
(95, 'Delaware DOT'),
(96, 'Iowa Environmental Mesonet'),
(97, 'Yuma Proving Ground');

